### ISSUE TITLE
Cannot find utils.py

### ISSUE THREAD

**Issue by Huangtianyu-caas** [kocherlab/HalictidCompGen#1]
Dear,

I was wondering if you can provide the code of **utils** module which you imported in the script selection_pipeline.py.(https://github.com/kocherlab/HalictidCompGen/blob/main/coding_evolution/selection_pipeline.py)

Because this module is important for the successful operation of selection_pipeline.py.

My best,
Tianyu Huang

**Comment by aewebb80** [comment]
Should be resolved by aab3fc8dc6321fe9b9bc0c7e8a6e0ea1af28ee3e. It's possible some of the modules has been updated, so let us know if there are any additional issues and we'll reopen the issue.
