### ISSUE TITLE
could not find the halictids.params file

### ISSUE THREAD

**Issue by aaannaw** [kocherlab/HalictidCompGen#2]
Hello,
I recently read your article: Convergent and complementary selection  shaped gains and losses of eusociality in  sweat bees. I am using the selection_pipeline.py script to run the command: python /Genomics/kocherlab/berubin/local/developing/selection_pipeline/selection_pipeline.py -b /Genomics/kocherlab/berubin/comparative/halictids/halictid_selection -o halictid -r /Genomics/kocherlab/berubin/comparative/halictids/orthology/orthofinder/protein_seqs/OrthoFinder/Results_Jan29_4/Orthogroups/Orthogroups.txt -t 2 -a write_orthos -d halictids.params. I can not find the  halictids.params file in https://github.com/kocherlab/HalictidCompGen/tree/main/homology/protein_coding_alignment. Could you give me any suggestions?
Best wishes! 
Na Wan

**Comment by aewebb80** [comment]
Hello,

See [74e9484](https://github.com/kocherlab/HalictidCompGen/commit/74e948434c42c0537c4b8c300afd5f08159716ab) for an example file. 

You may find the file [here](https://github.com/kocherlab/HalictidCompGen/blob/main/coding_evolution/selection_pipeline/halictids.params).

I'm marking this resolved for now but let us know if you have any issues with the file.
